### ISSUE TITLE
New Repo Dragon Rampant

### ISSUE THREAD

**Issue by silentpolygon** [BSData/bsdata#202] opened 2018-08-09 08:44 UTC
Hello,

I've begun to create Data Files for the Game Dragon Rampant by Osprey Publishing. The repo is at:

https://github.com/silentpolygon/BS_DragonRampant

I wolud be happy if it makes in the BSData Repo.

Kind regards
Thorsten

**Comment by amis92** [comment] 2018-08-09 12:52
First off, this is a duplicate of #109. Second, there seems to already be a game system and catalogue created. Which means you've duplicated the effort. And third, this is no longer valid place to request new repositories for game systems. Now the correct one is https://github.com/BSData/catalogue-development as laid out in [Getting Started](https://github.com/BSData/catalogue-development/wiki/Getting-Started#contributing)

I've checked the repo and it seems the original author (@Dogma2097) failed to follow guidelines as layed out in our wiki. Namely, there are `.catz/gstz` files (which cause the distribution system to skip the repo) and there is no Release made (so the dist. system doesn't even look at it).

If you wish to join that repo, please open an issue there, as suggested in the above linked Getting Started.

**Closed by amis92** 2018-08-09 12:52 UTC
Labels: duplicate, new-repo
