### ISSUE TITLE
Only 5 Repos available

### ISSUE THREAD

**Issue by JustusW** [BSData/bsdata#204] opened 2018-09-07 08:37 UTC
Currently there are only 5 repositories available, I could download more a few days ago, but now on Desktop and on Mobile almost none are available and all the ones I used are missing.

**Comment by amis92** [comment] 2018-10-02 19:52
Deprecated. Recurring issue, however for now I'm closing.

**Closed by amis92** 2018-10-02 19:52 UTC
Labels: bug

**Comment by MCyprien** [comment] 2018-10-10 09:11
Hello @amis92 
I don't understand what is deprecated, is there a solution to this issue ?

**Comment by JustusW** [comment] 2018-10-10 09:54
It means "we don't care it happens, deal with it"...

**Comment by amis92** [comment] 2018-10-10 10:57
There is no solution, and we are unable to conceive and deploy one. The web app developer is unavailable, the issue is widely known, although no reproducible scenario is known.

We do not know why it happens, we cannot fix it as Data Authors, and seemingly there is no willingness from the app developer to do so as well.

We're stuck as it is. So it is more of a duplicate, but there's no actual issue registered. which is what I'll fix now.

**Comment by amis92** [comment] 2018-10-10 13:47
Marking as duplicate of #208
