### ISSUE TITLE
New repo: Holotythe

### ISSUE THREAD

**Issue by DenOfImagination** [BSData/bsdata#266] opened 2023-06-15 09:05 UTC
name:Holotythe
Repository: https://github.com/DenOfImagination/Holotythe

I'm not sure if I'm doing things right. I've created a gamesystem and repository on github, now I'm wondering how to take another step :) Sorry if I'm too dumb ;)

**Comment by amis92** [comment] 2023-06-15 20:57
Duplicate of #265

**Closed by amis92** 2023-06-15 20:57 UTC
