### ISSUE TITLE
Repo Vanguard gone ????

### ISSUE THREAD

**Issue by BitPsycho** [BSData/bsdata#227] opened 2019-06-03 06:58 UTC
Hi,

The repository 'Kings of War - Vanguard' has disappeared from appspot ?  The latest release (8) was published 16 days ago and was there just fine ...  since then I didn't change anything.

http://battlescribedata.appspot.com/#/repo/kings-of-war-vanguard 

What happened ?

Thanks

**Comment by amis92** [comment] 2019-06-03 10:10
That's the repo for datasite issues

**Comment by amis92** [comment] 2019-06-03 10:11
Duplicate of #208

**Closed by amis92** 2019-06-03 10:11 UTC
